platform :ios, "8.0"
#inhibit_all_warnings!
target ‘weexDebugDemo’ do

  pod 'WeexSDK', '0.19.0.2'
  pod 'WXDevtool','0.16.3'
  pod 'SDWebImage', '3.7.5'
  pod 'SocketRocket', '0.4.2'
  pod 'ATSDK-Weex', '0.0.1',:configurations => ['Debug']
end








